server:
  port: 8082

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:parkingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:cGhzSmpSNXhRVXMyTTh2MVIweTl6S3FMNmFZd0I3blRnVnhjRjhkaEpxUjlzVmJXbU4wZVh5WjFyUTJ0VQ==}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}  # 1 hour in ms
