server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingdb
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  cloud:
      vault:
        uri: ${VAULT_ADDR:http://127.0.0.1:8200}
        token: ${VAULT_TOKEN:root}
        kv:
          enabled: true
          backend: secret
  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  title: Customer Service API
  description: Handles customer management
  version: 1.0.0
  group: customer-api
  security:
    enabled: true

jwt:
  secret: ${jwt.secret}
  expirationMs: ${jwt.expirationMs}
