server:
  port: 8087

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id:user-service-group
     auto-offset-reset:earliest