server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:parkingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:cGhzSmpSNXhRVXMyTTh2MVIweTl6S3FMNmFZd0I3blRnVnhjRjhkaEpxUjlzVmJXbU4wZVh5WjFyUTJ0VQ==}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

customer:
  service:
    url: http://customer-service:8082
